export const SHOW_HIDE_SIDEBAR = 'SHOW_HIDE_SIDEBAR';
export const ClEAR_ITEMS      =  'ClEAR_ITEMS ';
export const GET_ITEM_REQUEST = 'GET_ITEM_REQUEST';
export const GET_ITEM_SUCCESS = 'GET_ITEM_SUCCESS';
export const GET_ITEM_FAILURE = 'GET_ITEM_FAILURE';
export const GET_ITEM_USER_REQUEST = 'GET_ITEM_USER_REQUEST';
export const GET_ITEM_USER_SUCCESS = 'GET_ITEM_USER_SUCCESS';
export const GET_ITEM_USER_FAILURE = 'GET_ITEM_USER_FAILURE';